site_name: automate
site_description: Templatize patterns from your own codebase, make them programmable, then share them with your team
site_url: https://jezzsantos.github.io/automate/
repo_url: https://github.com/jezzsantos/automate/
edit_uri: edit/main/docs/
markdown_extensions:
  - toc:
      permalink: "#"
  - def_list
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - glightbox
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  logo: logo.svg
  font:
    # Any of the https://fonts.google.com/
    text: Source Sans Pro
    code: JetBrains Mono
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - 'Installing': 'installation.md'
  - 'How It Works': 'howitworks.md'
  - 'Evaluating automate': 'evaluating.md'
  - 'Your First Toolkit': 'tutorial.md'
  - 'Developers Guide':
      - 'Command Line (CLI)':
          - 'Installation': 'installation.md'
          - 'Using Toolkits': 'runtime.md'
          - 'Making Toolkits': 'authoring.md'
          - 'Additional Commands': 'cli.md'
      - 'IDE Plugin':
          - 'Installation': 'installation.md'
          - 'Using Toolkits': 'runtime-plugin.md'
          - 'Making Toolkits': 'authoring-plugin.md'
      - 'Reference': 'reference.md'
  - About:
      - 'GitHub': 'https://github.com/jezzsantos/automate'
      - 'License': 'https://github.com/jezzsantos/automate/blob/main/LICENSE'
      - 'Releases': 'https://github.com/jezzsantos/automate/releases'
      - 'Contributors': 'Contributors/contributors.md'
  - Privacy: 'privacy.md'
