//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automate.CLI.Infrastructure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OutputMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OutputMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Automate.CLI.Infrastructure.OutputMessages", typeof(OutputMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Attribute: &apos;{Name}&apos; (ID: &apos;{AttributeId}&apos;) to element &apos;{ParentId}&apos;, successfully.
        /// </summary>
        internal static string CommandLine_Output_AttributeAdded {
            get {
                return ResourceManager.GetString("CommandLine_Output_AttributeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Attribute: &apos;{Name}&apos; (ID: &apos;{AttributeId}&apos;) to element &apos;{ParentId}&apos;, successfully, with: required {IsRequired}, data-type {DataType}, default-value {DefaultValue}, and choices {Choices}.
        /// </summary>
        internal static string CommandLine_Output_AttributeAdded_ForStructured {
            get {
                return ResourceManager.GetString("CommandLine_Output_AttributeAdded_ForStructured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Attribute: &apos;{Name}&apos; (ID: &apos;{AttributeId}&apos;) from element &apos;{ParentId}&apos;, successfully.
        /// </summary>
        internal static string CommandLine_Output_AttributeDeleted {
            get {
                return ResourceManager.GetString("CommandLine_Output_AttributeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Attribute: &apos;{Name}&apos; (ID: &apos;{AttributeId}&apos;) on element &apos;{ParentId}&apos;, successfully.
        /// </summary>
        internal static string CommandLine_Output_AttributeUpdated {
            get {
                return ResourceManager.GetString("CommandLine_Output_AttributeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Attribute: &apos;{Name}&apos; (ID: &apos;{AttributeId}&apos;) to element &apos;{ParentId}&apos;, successfully, with: required {IsRequired}, data-type {DataType}, default-value {DefaultValue}, and choices {Choices}.
        /// </summary>
        internal static string CommandLine_Output_AttributeUpdated_ForStructured {
            get {
                return ResourceManager.GetString("CommandLine_Output_AttributeUpdated_ForStructured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolkit for pattern: &apos;{Name}&apos; has been built (v.{Version}), and is ready to be installed with command:
        ///`automate install toolkit &quot;{FilePath}&quot;`.
        /// </summary>
        internal static string CommandLine_Output_BuiltToolkit {
            get {
                return ResourceManager.GetString("CommandLine_Output_BuiltToolkit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: {Warning}.
        /// </summary>
        internal static string CommandLine_Output_BuiltToolkit_Warning {
            get {
                return ResourceManager.GetString("CommandLine_Output_BuiltToolkit_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added CLI Command: &apos;{Name}&apos; (ID: &apos;{CommandId}&apos;) to element &apos;{ParentId}&apos;.
        /// </summary>
        internal static string CommandLine_Output_CliCommandAdded {
            get {
                return ResourceManager.GetString("CommandLine_Output_CliCommandAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated CLI Command &apos;{Name}&apos; (ID: &apos;{CommandId}&apos;) on element &apos;{ParentId}&apos;, with app: {ApplicationName}, and Arguments: {Arguments}.
        /// </summary>
        internal static string CommandLine_Output_CliCommandUpdated {
            get {
                return ResourceManager.GetString("CommandLine_Output_CliCommandUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Code Template Command: &apos;{Name}&apos; (ID: &apos;{CommandId}&apos;) to element &apos;{ParentId}&apos;.
        /// </summary>
        internal static string CommandLine_Output_CodeTemplateCommandAdded {
            get {
                return ResourceManager.GetString("CommandLine_Output_CodeTemplateCommandAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Template Command &apos;{Name}&apos; (ID: &apos;{CommandId}&apos;) target path resolves to:
        ///{Output}.
        /// </summary>
        internal static string CommandLine_Output_CodeTemplateCommandTested {
            get {
                return ResourceManager.GetString("CommandLine_Output_CodeTemplateCommandTested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data from testing Code Template Command &apos;{Name}&apos; (ID: &apos;{CommandId}&apos;) has been exported to: &apos;{Exported}&apos;.
        /// </summary>
        internal static string CommandLine_Output_CodeTemplateCommandTestExported {
            get {
                return ResourceManager.GetString("CommandLine_Output_CodeTemplateCommandTestExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data for testing Code Template Command &apos;{Name}&apos; (ID: &apos;{CommandId}&apos;) was imported from: &apos;{Imported}&apos;.
        /// </summary>
        internal static string CommandLine_Output_CodeTemplateCommandTestImported {
            get {
                return ResourceManager.GetString("CommandLine_Output_CodeTemplateCommandTestImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Code Template Command &apos;{Name}&apos; (ID: &apos;{CommandId}&apos;) on element &apos;{ParentId}&apos;, with path: {FilePath}, and OneOff: {OneOff}.
        /// </summary>
        internal static string CommandLine_Output_CodeTemplateCommandUpdated {
            get {
                return ResourceManager.GetString("CommandLine_Output_CodeTemplateCommandUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Code Template: &apos;{Name}&apos; (ID: &apos;{Id}&apos;) to element &apos;{ParentId}&apos;, from: &apos;{FilePath}&apos;. Contents can be edited in: &apos;{EditorPath}&apos;.
        /// </summary>
        internal static string CommandLine_Output_CodeTemplatedAdded {
            get {
                return ResourceManager.GetString("CommandLine_Output_CodeTemplatedAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing Code Template: &apos;{Name}&apos; (ID: &apos;{Id}&apos;) on element &apos;{ParentId}&apos;, with &apos;{ApplicationPath}&apos; from &apos;{EditorPath}&apos;.
        /// </summary>
        internal static string CommandLine_Output_CodeTemplatedEdited {
            get {
                return ResourceManager.GetString("CommandLine_Output_CodeTemplatedEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Code Template: &apos;{Name}&apos; (ID: &apos;{Id}&apos;) from element &apos;{ParentId}&apos;.
        /// </summary>
        internal static string CommandLine_Output_CodeTemplateDeleted {
            get {
                return ResourceManager.GetString("CommandLine_Output_CodeTemplateDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Template &apos;{Name}&apos; (ID: &apos;{Id}&apos;) outputs:
        ///{Output}.
        /// </summary>
        internal static string CommandLine_Output_CodeTemplateTested {
            get {
                return ResourceManager.GetString("CommandLine_Output_CodeTemplateTested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data from testing Code Template &apos;{Name}&apos; (ID: &apos;{TemplateId}&apos;) has been exported to: &apos;{Exported}&apos;.
        /// </summary>
        internal static string CommandLine_Output_CodeTemplateTestExported {
            get {
                return ResourceManager.GetString("CommandLine_Output_CodeTemplateTestExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data for testing Code Template &apos;{Name}&apos; (ID: &apos;{TemplateId}&apos;) was imported from: &apos;{Imported}&apos;.
        /// </summary>
        internal static string CommandLine_Output_CodeTemplateTestImported {
            get {
                return ResourceManager.GetString("CommandLine_Output_CodeTemplateTestImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Collection: &apos;{Name}&apos; (ID: &apos;{ElementId}&apos;) to element &apos;{ParentId}&apos;, successfully.
        /// </summary>
        internal static string CommandLine_Output_CollectionAdded {
            get {
                return ResourceManager.GetString("CommandLine_Output_CollectionAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Collection: &apos;{Name}&apos; (ID: &apos;{ElementId}&apos;) to element &apos;{ParentId}&apos;, successfully, with: edit-path {EditPath}, display-name {DisplayName}, description {Description}, auto-create {AutoCreate}, cardinality {Cardinality}, and is-collection {IsCollection}.
        /// </summary>
        internal static string CommandLine_Output_CollectionAdded_ForStructured {
            get {
                return ResourceManager.GetString("CommandLine_Output_CollectionAdded_ForStructured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Collection: &apos;{Name}&apos; (ID: &apos;{ElementId}&apos;) from element &apos;{ParentId}&apos;, successfully.
        /// </summary>
        internal static string CommandLine_Output_CollectionDeleted {
            get {
                return ResourceManager.GetString("CommandLine_Output_CollectionDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Collection: &apos;{Name}&apos; (ID: &apos;{ElementId}&apos;) on element &apos;{ParentId}&apos;, successfully.
        /// </summary>
        internal static string CommandLine_Output_CollectionUpdated {
            get {
                return ResourceManager.GetString("CommandLine_Output_CollectionUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Collection: &apos;{Name}&apos; (ID: &apos;{ElementId}&apos;) on element &apos;{ParentId}&apos;, successfully, with: edit-path {EditPath}, display-name {DisplayName}, description {Description}, auto-create {AutoCreate}, cardinality {Cardinality}, and is-collection {IsCollection}.
        /// </summary>
        internal static string CommandLine_Output_CollectionUpdated_ForStructured {
            get {
                return ResourceManager.GetString("CommandLine_Output_CollectionUpdated_ForStructured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Command: &apos;{Name}&apos; (ID: &apos;{CommandId}&apos;) from element &apos;{ParentId}&apos;.
        /// </summary>
        internal static string CommandLine_Output_CommandDeleted {
            get {
                return ResourceManager.GetString("CommandLine_Output_CommandDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Command: &apos;{Command}&apos; did not completely succeed. Some commands failed:
        ///{Log}.
        /// </summary>
        internal static string CommandLine_Output_CommandExecutionFailed {
            get {
                return ResourceManager.GetString("CommandLine_Output_CommandExecutionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Command: &apos;{Command}&apos; was not executed. The draft is not correctly configured in these ways:
        ///{ValidationErrors}.
        /// </summary>
        internal static string CommandLine_Output_CommandExecutionFailed_WithValidation {
            get {
                return ResourceManager.GetString("CommandLine_Output_CommandExecutionFailed_WithValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Command: &apos;{Command}&apos; executed successfully:
        ///{Log}.
        /// </summary>
        internal static string CommandLine_Output_CommandExecutionSucceeded {
            get {
                return ResourceManager.GetString("CommandLine_Output_CommandExecutionSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drafts:
        ///{Drafts}.
        /// </summary>
        internal static string CommandLine_Output_ConfiguredDraftsListed {
            get {
                return ResourceManager.GetString("CommandLine_Output_ConfiguredDraftsListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created a new Draft &apos;{DraftName}&apos; (ID: &apos;{DraftId}&apos;) from toolkit: &apos;{ToolkitName}&apos; (ID: &apos;{ToolkitId}&apos;, v.{ToolkitVersion}, rt.v{RuntimeVersion}).
        /// </summary>
        internal static string CommandLine_Output_CreateDraftFromToolkit {
            get {
                return ResourceManager.GetString("CommandLine_Output_CreateDraftFromToolkit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft &apos;{DraftName}&apos; (ID: &apos;{DraftId}&apos;) from toolkit: &apos;{ToolkitName}&apos; (ID: &apos;{ToolkitId}&apos;, v.{ToolkitVersion}, rt.v{RuntimeVersion}) is configured as:
        ///{Configuration}.
        /// </summary>
        internal static string CommandLine_Output_DraftConfiguration {
            get {
                return ResourceManager.GetString("CommandLine_Output_DraftConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Draft Item &apos;{Name}&apos; (ID: &apos;{DraftItemId}&apos;) was configured successfully, as:
        ///{Configuration}.
        /// </summary>
        internal static string CommandLine_Output_DraftConfigured {
            get {
                return ResourceManager.GetString("CommandLine_Output_DraftConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted Draft &apos;{DraftName}&apos; (ID: &apos;{DraftId}&apos;), and reset the current draft.
        /// </summary>
        internal static string CommandLine_Output_DraftDeleted {
            get {
                return ResourceManager.GetString("CommandLine_Output_DraftDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Draft Item &apos;{Name}&apos; (ID: &apos;{DraftItemId}&apos;) was deleted successfully.
        /// </summary>
        internal static string CommandLine_Output_DraftDeleteElement {
            get {
                return ResourceManager.GetString("CommandLine_Output_DraftDeleteElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Draft Item &apos;{Name}&apos; (ID: &apos;{DraftItemId}&apos;) was cleared successfully.
        /// </summary>
        internal static string CommandLine_Output_DraftEmptyCollection {
            get {
                return ResourceManager.GetString("CommandLine_Output_DraftEmptyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Draft Item &apos;{Name}&apos; (ID: &apos;{DraftItemId}&apos;) was reset successfully.
        /// </summary>
        internal static string CommandLine_Output_DraftResetElement {
            get {
                return ResourceManager.GetString("CommandLine_Output_DraftResetElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Draft: &apos;{DraftName}&apos; (ID: &apos;{DraftId}&apos;) from toolkit: &apos;{ToolkitName}&apos; (ID: &apos;{ToolkitId}&apos;, v.{ToolkitVersion} rt.v{RuntimeVersion}), is now the default.
        /// </summary>
        internal static string CommandLine_Output_DraftSwitched {
            get {
                return ResourceManager.GetString("CommandLine_Output_DraftSwitched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully upgraded Draft &apos;{DraftName}&apos; (ID: &apos;{DraftId}&apos;) from toolkit &apos;{ToolkitName}&apos; ({OldVersion} -&gt; {NewVersion}):
        ///{Log}.
        /// </summary>
        internal static string CommandLine_Output_DraftUpgradeSucceeded {
            get {
                return ResourceManager.GetString("CommandLine_Output_DraftUpgradeSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborted upgrade of Draft &apos;{DraftName}&apos; (ID: &apos;{DraftId}&apos;) from toolkit &apos;{ToolkitName}&apos; ({OldVersion} -&gt; {NewVersion}):
        ///{Log}.
        /// </summary>
        internal static string CommandLine_Output_DraftUpgradeWithWarning {
            get {
                return ResourceManager.GetString("CommandLine_Output_DraftUpgradeWithWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft &apos;{Name}&apos; (ID: &apos;{Id}&apos;) is not correctly configured in these ways:
        ///{Errors}.
        /// </summary>
        internal static string CommandLine_Output_DraftValidationFailed {
            get {
                return ResourceManager.GetString("CommandLine_Output_DraftValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft &apos;{Name}&apos; (ID: &apos;{Id}&apos;) is configured correctly.
        /// </summary>
        internal static string CommandLine_Output_DraftValidationSuccess {
            get {
                return ResourceManager.GetString("CommandLine_Output_DraftValidationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editable patterns:
        ///{Patterns}.
        /// </summary>
        internal static string CommandLine_Output_EditablePatternsListed {
            get {
                return ResourceManager.GetString("CommandLine_Output_EditablePatternsListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Element: &apos;{Name}&apos; (ID: &apos;{ElementId}&apos;) to element &apos;{ParentId}&apos;, successfully.
        /// </summary>
        internal static string CommandLine_Output_ElementAdded {
            get {
                return ResourceManager.GetString("CommandLine_Output_ElementAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Element: &apos;{Name}&apos; (ID: &apos;{ElementId}&apos;) to element &apos;{ParentId}&apos;, successfully, with: edit-path {EditPath}, display-name {DisplayName}, description {Description}, auto-create {AutoCreate}, cardinality {Cardinality}, and is-collection {IsCollection}.
        /// </summary>
        internal static string CommandLine_Output_ElementAdded_ForStructured {
            get {
                return ResourceManager.GetString("CommandLine_Output_ElementAdded_ForStructured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Element: &apos;{Name}&apos; (ID: &apos;{ElementId}&apos;) from element &apos;{ParentId}&apos;, successfully.
        /// </summary>
        internal static string CommandLine_Output_ElementDeleted {
            get {
                return ResourceManager.GetString("CommandLine_Output_ElementDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Element: &apos;{Name}&apos; (ID: &apos;{ElementId}&apos;) on element &apos;{ParentId}&apos;, successfully.
        /// </summary>
        internal static string CommandLine_Output_ElementUpdated {
            get {
                return ResourceManager.GetString("CommandLine_Output_ElementUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Element: &apos;{Name}&apos; (ID: &apos;{ElementId}&apos;) on element &apos;{ParentId}&apos;, successfully, with: edit-path {EditPath}, display-name {DisplayName}, description {Description}, auto-create {AutoCreate}, cardinality {Cardinality}, and is-collection {IsCollection}.
        /// </summary>
        internal static string CommandLine_Output_ElementUpdated_ForStructured {
            get {
                return ResourceManager.GetString("CommandLine_Output_ElementUpdated_ForStructured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything is up to date.
        /// </summary>
        internal static string CommandLine_Output_ExecuteLaunchPointSucceededNoOutput {
            get {
                return ResourceManager.GetString("CommandLine_Output_ExecuteLaunchPointSucceededNoOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolkit for pattern: &apos;{Name}&apos; (v.{Version}) has been installed and is ready to use with command:
        ///`automate run toolkit &lt;PatternName&gt; --name &quot;DraftName&quot;`.
        /// </summary>
        internal static string CommandLine_Output_InstalledToolkit {
            get {
                return ResourceManager.GetString("CommandLine_Output_InstalledToolkit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed toolkits:
        ///{Toolkits}.
        /// </summary>
        internal static string CommandLine_Output_InstalledToolkitsListed {
            get {
                return ResourceManager.GetString("CommandLine_Output_InstalledToolkitsListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Launch Point &apos;{Name}&apos; (ID: &apos;{LaunchPointId}&apos;) to element &apos;{ParentId}&apos;, for commands: {Commands}.
        /// </summary>
        internal static string CommandLine_Output_LaunchPointAdded {
            get {
                return ResourceManager.GetString("CommandLine_Output_LaunchPointAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Launch Point &apos;{Name}&apos; (ID: &apos;{LaunchPointId}&apos;) from element &apos;{ParentId}&apos;.
        /// </summary>
        internal static string CommandLine_Output_LaunchPointDeleted {
            get {
                return ResourceManager.GetString("CommandLine_Output_LaunchPointDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Launch Point &apos;{Name}&apos; (ID: &apos;{LaunchPointId}&apos;) on element &apos;{ParentId}&apos;, with commands: {Commands}.
        /// </summary>
        internal static string CommandLine_Output_LaunchPointUpdated {
            get {
                return ResourceManager.GetString("CommandLine_Output_LaunchPointUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no configured Drafts yet. Use this command to create one:
        ///`automate run toolkit &lt;PatternName&gt; --name &lt;DraftName&gt;`.
        /// </summary>
        internal static string CommandLine_Output_NoConfiguredDrafts {
            get {
                return ResourceManager.GetString("CommandLine_Output_NoConfiguredDrafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no editable Patterns yet. Use this command to create one:
        ///`automate create pattern &lt;PatternName&gt;`.
        /// </summary>
        internal static string CommandLine_Output_NoEditablePatterns {
            get {
                return ResourceManager.GetString("CommandLine_Output_NoEditablePatterns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no installed Toolkits yet. Use this command to install one:
        ///`automate install toolkit &lt;Location&gt;`.
        /// </summary>
        internal static string CommandLine_Output_NoInstalledToolkits {
            get {
                return ResourceManager.GetString("CommandLine_Output_NoInstalledToolkits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pattern: &apos;{Name}&apos; (v.{Version}) was created with ID: {PatternId}.
        /// </summary>
        internal static string CommandLine_Output_PatternCreated {
            get {
                return ResourceManager.GetString("CommandLine_Output_PatternCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern &apos;{Name}&apos; (ID: &apos;{PatternId}&apos;, v{Version}) has these launch points available:
        ///{LaunchPoints}.
        /// </summary>
        internal static string CommandLine_Output_PatternLaunchableAutomation {
            get {
                return ResourceManager.GetString("CommandLine_Output_PatternLaunchableAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern &apos;{Name}&apos; (ID: &apos;{PatternId}&apos;, v{Version}) is defined as:
        ///{Schema}.
        /// </summary>
        internal static string CommandLine_Output_PatternSchema {
            get {
                return ResourceManager.GetString("CommandLine_Output_PatternSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pattern: &apos;{Name}&apos; (v.{Version}) (ID: &apos;{PatternId}&apos;) is now the default.
        /// </summary>
        internal static string CommandLine_Output_PatternSwitched {
            get {
                return ResourceManager.GetString("CommandLine_Output_PatternSwitched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pattern: &apos;{Name}&apos; was updated.
        /// </summary>
        internal static string CommandLine_Output_PatternUpdated {
            get {
                return ResourceManager.GetString("CommandLine_Output_PatternUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Draft: &apos;{Name}&apos; (ID: &apos;{Id}&apos;) is now being configured.
        /// </summary>
        internal static string CommandLine_Output_Preamble_CurrentDraftInUse {
            get {
                return ResourceManager.GetString("CommandLine_Output_Preamble_CurrentDraftInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pattern: &apos;{Name}&apos; (v.{Version}) is now being edited.
        /// </summary>
        internal static string CommandLine_Output_Preamble_CurrentPatternInUse {
            get {
                return ResourceManager.GetString("CommandLine_Output_Preamble_CurrentPatternInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Draft is being configured. You must first run one of these commands:
        ///`automate run toolkit &lt;PatternName&gt; --name &lt;DraftName&gt;` to create a new draft from an existing toolkit, or
        ///`automate run switch &lt;DraftID&gt;` to switch to this existing draft.
        /// </summary>
        internal static string CommandLine_Output_Preamble_NoDraftSelected {
            get {
                return ResourceManager.GetString("CommandLine_Output_Preamble_NoDraftSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Pattern is being edited. You must first run one of these commands:
        ///`automate create pattern &lt;Name&gt;` to create a new pattern, or
        ///`automate edit switch &lt;Name&gt;` to switch to an existing pattern.
        /// </summary>
        internal static string CommandLine_Output_Preamble_NoPatternSelected {
            get {
                return ResourceManager.GetString("CommandLine_Output_Preamble_NoPatternSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is only for testingonly.
        /// </summary>
        internal static string CommandLine_Output_Preamble_TestingOnly {
            get {
                return ResourceManager.GetString("CommandLine_Output_Preamble_TestingOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amessagetemplate {aname}.
        /// </summary>
        internal static string CommandLine_Output_TestingOnly {
            get {
                return ResourceManager.GetString("CommandLine_Output_TestingOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templating Expression Language Reference: https://github.com/scriban/scriban/tree/master/doc.
        /// </summary>
        internal static string CommandLine_Output_TextTemplatingExpressionReference {
            get {
                return ResourceManager.GetString("CommandLine_Output_TextTemplatingExpressionReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolkit pattern &apos;{Name}&apos; (ID: &apos;{Id}&apos;, v{Version}, rt.v{RuntimeVersion}) is defined as:
        ///{Schema}.
        /// </summary>
        internal static string CommandLine_Output_ToolkitSchema {
            get {
                return ResourceManager.GetString("CommandLine_Output_ToolkitSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgraded without any changes.
        /// </summary>
        internal static string CommandLine_Output_UpgradedDraftSucceededNoOutput {
            get {
                return ResourceManager.GetString("CommandLine_Output_UpgradedDraftSucceededNoOutput", resourceCulture);
            }
        }
    }
}
