//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automate.CLI.Infrastructure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OutputMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OutputMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Automate.CLI.Infrastructure.OutputMessages", typeof(OutputMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Attribute: &apos;{Name}&apos; (ID: &apos;{AttributeId}&apos;) to element &apos;{ParentId}&apos;.
        /// </summary>
        internal static string CommandLine_Output_AttributeAdded {
            get {
                return ResourceManager.GetString("CommandLine_Output_AttributeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Attribute: &apos;{Name}&apos; (ID: &apos;{AttributeId}&apos;) from element &apos;{ParentId}&apos;.
        /// </summary>
        internal static string CommandLine_Output_AttributeDeleted {
            get {
                return ResourceManager.GetString("CommandLine_Output_AttributeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Attribute: &apos;{Name}&apos; (ID: &apos;{AttributeId}&apos;) on element &apos;{ParentId}&apos;, successfully.
        /// </summary>
        internal static string CommandLine_Output_AttributeUpdated {
            get {
                return ResourceManager.GetString("CommandLine_Output_AttributeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolkit for pattern: &apos;{Name}&apos; has been built (v.{Version}), and is ready to be installed with command:
        ///`automate install toolkit &quot;{&lt;FilePath&gt;}&quot;`.
        /// </summary>
        internal static string CommandLine_Output_BuiltToolkit {
            get {
                return ResourceManager.GetString("CommandLine_Output_BuiltToolkit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: {Warning}.
        /// </summary>
        internal static string CommandLine_Output_BuiltToolkit_Warning {
            get {
                return ResourceManager.GetString("CommandLine_Output_BuiltToolkit_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added CLI Command: &apos;{Name}&apos; (ID: &apos;{CommandId}&apos;) to element &apos;{ParentId}&apos;.
        /// </summary>
        internal static string CommandLine_Output_CliCommandAdded {
            get {
                return ResourceManager.GetString("CommandLine_Output_CliCommandAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated CLI Command &apos;{Name}&apos; (ID: &apos;{CommandId}&apos;) on element &apos;{ParentId}&apos;, with app: {ApplicationName}, and Arguments: {Arguments}.
        /// </summary>
        internal static string CommandLine_Output_CliCommandUpdated {
            get {
                return ResourceManager.GetString("CommandLine_Output_CliCommandUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Code Template Command: &apos;{Name}&apos; (ID: &apos;{CommandId}&apos;) to element &apos;{ParentId}&apos;.
        /// </summary>
        internal static string CommandLine_Output_CodeTemplateCommandAdded {
            get {
                return ResourceManager.GetString("CommandLine_Output_CodeTemplateCommandAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Code Template Command &apos;{Name}&apos; (ID: &apos;{CommandId}&apos;) on element &apos;{ParentId}&apos;, with path: {FilePath}, and OneOff: {OneOff}.
        /// </summary>
        internal static string CommandLine_Output_CodeTemplateCommandUpdated {
            get {
                return ResourceManager.GetString("CommandLine_Output_CodeTemplateCommandUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Code Template: &apos;{Name}&apos; (ID: &apos;{Id}&apos;) to element &apos;{ParentId}&apos;, from: &apos;{FilePath}&apos;. Contents can be edited in: &apos;{EditorPath}&apos;.
        /// </summary>
        internal static string CommandLine_Output_CodeTemplatedAdded {
            get {
                return ResourceManager.GetString("CommandLine_Output_CodeTemplatedAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing Code Template: &apos;{Name}&apos; (ID: &apos;{Id}&apos;) on element &apos;{ParentId}&apos;, with &apos;{ApplicationPath}&apos; from &apos;{EditorPath}&apos;.
        /// </summary>
        internal static string CommandLine_Output_CodeTemplatedEdited {
            get {
                return ResourceManager.GetString("CommandLine_Output_CodeTemplatedEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Code Template: &apos;{Name}&apos; (ID: &apos;{Id}&apos;) from element &apos;{ParentId}&apos;.
        /// </summary>
        internal static string CommandLine_Output_CodeTemplateDeleted {
            get {
                return ResourceManager.GetString("CommandLine_Output_CodeTemplateDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Template &apos;{Name}&apos; (ID: &apos;{Id}&apos;) outputs:
        ///{Output}.
        /// </summary>
        internal static string CommandLine_Output_CodeTemplateTested {
            get {
                return ResourceManager.GetString("CommandLine_Output_CodeTemplateTested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data from testing Code Template &apos;{Name}&apos; (ID: &apos;{Id}&apos;) has been exported to: &apos;{Exported}&apos;.
        /// </summary>
        internal static string CommandLine_Output_CodeTemplateTestExported {
            get {
                return ResourceManager.GetString("CommandLine_Output_CodeTemplateTestExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data for testing Code Template &apos;{Name}&apos; (ID: &apos;{Id}&apos;) was imported from: &apos;{Imported}&apos;.
        /// </summary>
        internal static string CommandLine_Output_CodeTemplateTestImported {
            get {
                return ResourceManager.GetString("CommandLine_Output_CodeTemplateTestImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Collection: &apos;{Name}&apos; (ID: &apos;{ElementId}&apos;) to element &apos;{ParentId}&apos;.
        /// </summary>
        internal static string CommandLine_Output_CollectionAdded {
            get {
                return ResourceManager.GetString("CommandLine_Output_CollectionAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Collection: &apos;{Name}&apos; (ID: &apos;{ElementId}&apos;) from element &apos;{ParentId}&apos;.
        /// </summary>
        internal static string CommandLine_Output_CollectionDeleted {
            get {
                return ResourceManager.GetString("CommandLine_Output_CollectionDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Collection: &apos;{Name}&apos; (ID: &apos;{ElementId}&apos;) on element &apos;{ParentId}&apos;, successfully.
        /// </summary>
        internal static string CommandLine_Output_CollectionUpdated {
            get {
                return ResourceManager.GetString("CommandLine_Output_CollectionUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Command: &apos;{Name}&apos; (ID: &apos;{CommandId}&apos;) from element &apos;{ParentId}&apos;.
        /// </summary>
        internal static string CommandLine_Output_CommandDeleted {
            get {
                return ResourceManager.GetString("CommandLine_Output_CommandDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Command: &apos;{Command}&apos; did not completely succeed. Some commands failed:
        ///{Log}.
        /// </summary>
        internal static string CommandLine_Output_CommandExecutionFailed {
            get {
                return ResourceManager.GetString("CommandLine_Output_CommandExecutionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Command: &apos;{Command}&apos; executed successfully:
        ///{Log}.
        /// </summary>
        internal static string CommandLine_Output_CommandExecutionSucceeded {
            get {
                return ResourceManager.GetString("CommandLine_Output_CommandExecutionSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created a new Draft &apos;{Name}&apos; (ID: &apos;{DraftId}&apos;) from toolkit: &apos;{PatternName}&apos;.
        /// </summary>
        internal static string CommandLine_Output_CreateDraftFromToolkit {
            get {
                return ResourceManager.GetString("CommandLine_Output_CreateDraftFromToolkit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Draft: &apos;{Name}&apos; (ID: &apos;{DraftId}&apos;) is now being configured.
        /// </summary>
        internal static string CommandLine_Output_CurrentDraftInUse {
            get {
                return ResourceManager.GetString("CommandLine_Output_CurrentDraftInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pattern: &apos;{Name}&apos; (v.{Version}) is now being edited.
        /// </summary>
        internal static string CommandLine_Output_CurrentPatternInUse {
            get {
                return ResourceManager.GetString("CommandLine_Output_CurrentPatternInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft &apos;{Name}&apos; (ID: &apos;{DraftId}&apos;) is configured as:
        ///{Configuration}.
        /// </summary>
        internal static string CommandLine_Output_DraftConfiguration {
            get {
                return ResourceManager.GetString("CommandLine_Output_DraftConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Draft Item &apos;{raftName}&apos; (ID: &apos;{DraftItemId}&apos;) was configured successfully.
        /// </summary>
        internal static string CommandLine_Output_DraftConfigured {
            get {
                return ResourceManager.GetString("CommandLine_Output_DraftConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Draft Item &apos;{Name}&apos; (ID: &apos;{DraftItemId}&apos;) was deleted successfully.
        /// </summary>
        internal static string CommandLine_Output_DraftDelete {
            get {
                return ResourceManager.GetString("CommandLine_Output_DraftDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Draft Item &apos;{Name}&apos; (ID: &apos;{DraftItemId}&apos;) was cleared successfully.
        /// </summary>
        internal static string CommandLine_Output_DraftEmptyCollection {
            get {
                return ResourceManager.GetString("CommandLine_Output_DraftEmptyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Draft Item &apos;{Name}&apos; (ID: &apos;{DraftItemId}&apos;) was reset successfully.
        /// </summary>
        internal static string CommandLine_Output_DraftResetElement {
            get {
                return ResourceManager.GetString("CommandLine_Output_DraftResetElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Draft: &apos;{Name}&apos; (ID: &apos;{DraftId}&apos;) is now the default.
        /// </summary>
        internal static string CommandLine_Output_DraftSwitched {
            get {
                return ResourceManager.GetString("CommandLine_Output_DraftSwitched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to upgrade Draft &apos;{Name}&apos; (ID: &apos;{DraftId}&apos;) from toolkit &apos;{ToolkitName}&apos; ({OldVersion} -&gt; {NewVersion}):
        ///{Log}.
        /// </summary>
        internal static string CommandLine_Output_DraftUpgradeFailed {
            get {
                return ResourceManager.GetString("CommandLine_Output_DraftUpgradeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully upgraded Draft &apos;{Name}&apos; (ID: &apos;{DraftId}&apos;) from toolkit &apos;{ToolkitName}&apos; ({OldVersion} -&gt; {NewVersion}):
        ///{Log}.
        /// </summary>
        internal static string CommandLine_Output_DraftUpgradeSucceeded {
            get {
                return ResourceManager.GetString("CommandLine_Output_DraftUpgradeSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborted upgrade of Draft &apos;{Name}&apos; (ID: &apos;{DraftId}&apos;) from toolkit &apos;{ToolkitName}&apos; ({OldVersion} -&gt; {NewVersion}):
        ///{Log}.
        /// </summary>
        internal static string CommandLine_Output_DraftUpgradeWithWarning {
            get {
                return ResourceManager.GetString("CommandLine_Output_DraftUpgradeWithWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft &apos;{Name}&apos; (ID: &apos;{DraftId}&apos;) is not correctly configured in these ways:
        ///{Errors}.
        /// </summary>
        internal static string CommandLine_Output_DraftValidationFailed {
            get {
                return ResourceManager.GetString("CommandLine_Output_DraftValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft &apos;{Name}&apos; (ID: &apos;{DraftId}&apos;) is configured correctly.
        /// </summary>
        internal static string CommandLine_Output_DraftValidationSuccess {
            get {
                return ResourceManager.GetString("CommandLine_Output_DraftValidationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editable patterns:
        ///{Patterns}.
        /// </summary>
        internal static string CommandLine_Output_EditablePatternsListed {
            get {
                return ResourceManager.GetString("CommandLine_Output_EditablePatternsListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Element: &apos;{Name}&apos; (ID: &apos;{ElementId}&apos;) to element &apos;{ParentId}&apos;.
        /// </summary>
        internal static string CommandLine_Output_ElementAdded {
            get {
                return ResourceManager.GetString("CommandLine_Output_ElementAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Element: &apos;{Name}&apos; (ID: &apos;{ElementId}&apos;) from element &apos;{ParentId}&apos;.
        /// </summary>
        internal static string CommandLine_Output_ElementDeleted {
            get {
                return ResourceManager.GetString("CommandLine_Output_ElementDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Element: &apos;{Name}&apos; (ID: &apos;{ElementId}&apos;) on element &apos;{ParentId}&apos;, successfully.
        /// </summary>
        internal static string CommandLine_Output_ElementUpdated {
            get {
                return ResourceManager.GetString("CommandLine_Output_ElementUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Drafts:
        ///{Drafts}.
        /// </summary>
        internal static string CommandLine_Output_InstalledDraftsListed {
            get {
                return ResourceManager.GetString("CommandLine_Output_InstalledDraftsListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolkit for pattern: &apos;{Name}&apos; (v.{Version}) has been installed and is ready to use with command:
        ///`automate run toolkit &lt;PatternName&gt; --name &quot;DraftName&quot;`.
        /// </summary>
        internal static string CommandLine_Output_InstalledToolkit {
            get {
                return ResourceManager.GetString("CommandLine_Output_InstalledToolkit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed toolkits:
        ///{Toolkits}.
        /// </summary>
        internal static string CommandLine_Output_InstalledToolkitsListed {
            get {
                return ResourceManager.GetString("CommandLine_Output_InstalledToolkitsListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Launch Point &apos;{Name}&apos; (ID: &apos;{LaunchPointId}&apos;) to element &apos;{ParentId}&apos;, for commands: {Commands}.
        /// </summary>
        internal static string CommandLine_Output_LaunchPointAdded {
            get {
                return ResourceManager.GetString("CommandLine_Output_LaunchPointAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Launch Point &apos;{Name}&apos; (ID: &apos;{LaunchPointId}&apos;) from element &apos;{ParentId}&apos;.
        /// </summary>
        internal static string CommandLine_Output_LaunchPointDeleted {
            get {
                return ResourceManager.GetString("CommandLine_Output_LaunchPointDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Launch Point &apos;{Name}&apos; (ID: &apos;{LaunchPointId}&apos;) on element &apos;{ParentId}&apos;, with commands: {Commands}.
        /// </summary>
        internal static string CommandLine_Output_LaunchPointUpdated {
            get {
                return ResourceManager.GetString("CommandLine_Output_LaunchPointUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Draft is being configured. You must first run one of these commands:
        ///`automate run toolkit &lt;PatternName&gt; --name &lt;DraftName&gt;` to create a new draft from an existing toolkit, or
        ///`automate run switch &lt;DraftID&gt;` to switch to this existing draft.
        /// </summary>
        internal static string CommandLine_Output_NoDraftSelected {
            get {
                return ResourceManager.GetString("CommandLine_Output_NoDraftSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no editable Patterns yet.
        /// </summary>
        internal static string CommandLine_Output_NoEditablePatterns {
            get {
                return ResourceManager.GetString("CommandLine_Output_NoEditablePatterns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no Drafts yet. Use this command to create one:
        ///`automate run toolkit &lt;PatternName&gt; --name &lt;DraftName&gt;`.
        /// </summary>
        internal static string CommandLine_Output_NoInstalledDrafts {
            get {
                return ResourceManager.GetString("CommandLine_Output_NoInstalledDrafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no installed Toolkits yet.
        /// </summary>
        internal static string CommandLine_Output_NoInstalledToolkits {
            get {
                return ResourceManager.GetString("CommandLine_Output_NoInstalledToolkits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Pattern is being edited. You must first run one of these commands:
        ///`automate pattern create &lt;Name&gt;` to create a new pattern, or
        ///`automate pattern use &lt;Name&gt;` to switch to this existing pattern.
        /// </summary>
        internal static string CommandLine_Output_NoPatternSelected {
            get {
                return ResourceManager.GetString("CommandLine_Output_NoPatternSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern is configured as:
        ///{Tree}.
        /// </summary>
        internal static string CommandLine_Output_PatternConfiguration {
            get {
                return ResourceManager.GetString("CommandLine_Output_PatternConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pattern: &apos;{Name}&apos; was created with ID: {PatternId}.
        /// </summary>
        internal static string CommandLine_Output_PatternCreated {
            get {
                return ResourceManager.GetString("CommandLine_Output_PatternCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pattern: &apos;{Name}&apos; (ID: &apos;{PatternId}&apos;) is now the default.
        /// </summary>
        internal static string CommandLine_Output_PatternSwitched {
            get {
                return ResourceManager.GetString("CommandLine_Output_PatternSwitched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pattern: &apos;{Name}&apos; was updated.
        /// </summary>
        internal static string CommandLine_Output_PatternUpdated {
            get {
                return ResourceManager.GetString("CommandLine_Output_PatternUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolkit pattern is defined as:
        ///{Tree}.
        /// </summary>
        internal static string CommandLine_Output_ToolkitConfiguration {
            get {
                return ResourceManager.GetString("CommandLine_Output_ToolkitConfiguration", resourceCulture);
            }
        }
    }
}
