//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automate.Authoring.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VersionChanges {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VersionChanges() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Automate.Authoring.Domain.VersionChanges", typeof(VersionChanges).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute (ID: {AttributeId}) was updated on element {ParentId}, and changed its choices.
        /// </summary>
        internal static string Attribute_Update_Choices {
            get {
                return ResourceManager.GetString("Attribute_Update_Choices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute (ID: {AttributeId}) was updated on element {ParentId}, and changed its data type.
        /// </summary>
        internal static string Attribute_Update_DataType {
            get {
                return ResourceManager.GetString("Attribute_Update_DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute (ID: {AttributeId}) was updated on element {ParentId}, and changed its default value.
        /// </summary>
        internal static string Attribute_Update_DefaultValue {
            get {
                return ResourceManager.GetString("Attribute_Update_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute (ID: {AttributeId}) was updated on element {ParentId}, and changed its name.
        /// </summary>
        internal static string Attribute_Update_Name {
            get {
                return ResourceManager.GetString("Attribute_Update_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute (ID: {AttributeId}) was updated on element {ParentId}, and changed whether it is required.
        /// </summary>
        internal static string Attribute_Update_Required {
            get {
                return ResourceManager.GetString("Attribute_Update_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automation (ID: {AutomationId}) was updated on element {ParentId}, and changed its metadata.
        /// </summary>
        internal static string Automation_Update_Metadata {
            get {
                return ResourceManager.GetString("Automation_Update_Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automation (ID: {AutomationId}) was updated on element {ParentId}, and changed its name.
        /// </summary>
        internal static string Automation_Update_Name {
            get {
                return ResourceManager.GetString("Automation_Update_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element (ID: {ElementId}) was updated on element {ParentId}, and changed its description.
        /// </summary>
        internal static string Element_Update_Description {
            get {
                return ResourceManager.GetString("Element_Update_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element (ID: {ElementId}) was updated on element {ParentId}, and changed its display name.
        /// </summary>
        internal static string Element_Update_DisplayName {
            get {
                return ResourceManager.GetString("Element_Update_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element (ID: {ElementId}) was updated on element {ParentId}, and changed its name.
        /// </summary>
        internal static string Element_Update_Name {
            get {
                return ResourceManager.GetString("Element_Update_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeTemplate (ID: {TemplateId}) was modified on element {ParentId}.
        /// </summary>
        internal static string Pattern_CodeTemplates_Update {
            get {
                return ResourceManager.GetString("Pattern_CodeTemplates_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern (ID: {PatternId}) changed its description.
        /// </summary>
        internal static string Pattern_Description_Updated {
            get {
                return ResourceManager.GetString("Pattern_Description_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern (ID: {PatternId}) changed its display name.
        /// </summary>
        internal static string Pattern_DisplayName_Updated {
            get {
                return ResourceManager.GetString("Pattern_DisplayName_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern (ID: {PatternId}) changed its name.
        /// </summary>
        internal static string Pattern_Name_Updated {
            get {
                return ResourceManager.GetString("Pattern_Name_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute (ID: {AttributeId}) was added to element {ParentId}.
        /// </summary>
        internal static string PatternElement_Attribute_Add {
            get {
                return ResourceManager.GetString("PatternElement_Attribute_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute (ID: {AttributeId}) was deleted from element {ParentId}.
        /// </summary>
        internal static string PatternElement_Attribute_Delete {
            get {
                return ResourceManager.GetString("PatternElement_Attribute_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automation (ID: {AutomationId}) was added to element {ParentId}.
        /// </summary>
        internal static string PatternElement_Automation_Add {
            get {
                return ResourceManager.GetString("PatternElement_Automation_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automation (ID: {AutomationId}) was deleted from element {ParentId}.
        /// </summary>
        internal static string PatternElement_Automation_Delete {
            get {
                return ResourceManager.GetString("PatternElement_Automation_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CliCommand (ID: {AutomationId}) was deleted from element {ParentId}.
        /// </summary>
        internal static string PatternElement_CliCommand_Delete {
            get {
                return ResourceManager.GetString("PatternElement_CliCommand_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeTemplate (ID: {TemplateId}) was added to element {ParentId}.
        /// </summary>
        internal static string PatternElement_CodeTemplate_Add {
            get {
                return ResourceManager.GetString("PatternElement_CodeTemplate_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeTemplate (ID: {TemplateId}) was deleted from element {ParentId}.
        /// </summary>
        internal static string PatternElement_CodeTemplate_Delete {
            get {
                return ResourceManager.GetString("PatternElement_CodeTemplate_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeTemplateCommand (ID: {AutomationId}) was deleted from element {ParentId}.
        /// </summary>
        internal static string PatternElement_CodeTemplateCommand_Delete {
            get {
                return ResourceManager.GetString("PatternElement_CodeTemplateCommand_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandLaunchPoint (ID: {AutomationId}) was deleted from element {ParentId}.
        /// </summary>
        internal static string PatternElement_CommandLaunchPoint_Delete {
            get {
                return ResourceManager.GetString("PatternElement_CommandLaunchPoint_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element/Collection (ID: {ElementId}) was added to element {ParentId}.
        /// </summary>
        internal static string PatternElement_Element_Add {
            get {
                return ResourceManager.GetString("PatternElement_Element_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element (ID: {ElementId}) was deleted from element {ParentId}.
        /// </summary>
        internal static string PatternElement_Element_Delete {
            get {
                return ResourceManager.GetString("PatternElement_Element_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element (ID: {ElementId}) was updated on element {ParentId}, and changed its auto-creation.
        /// </summary>
        internal static string PatternElement_Element_Update_AutoCreate {
            get {
                return ResourceManager.GetString("PatternElement_Element_Update_AutoCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element (ID: {ElementId}) was updated on element {ParentId}, and changed its cardinality.
        /// </summary>
        internal static string PatternElement_Element_Update_Cardinality {
            get {
                return ResourceManager.GetString("PatternElement_Element_Update_Cardinality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolkit was upgraded from v.{Old} to v.{New}.
        /// </summary>
        internal static string ToolkitVersion_NewVersion {
            get {
                return ResourceManager.GetString("ToolkitVersion_NewVersion", resourceCulture);
            }
        }
    }
}
