name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore src/Automate.sln
      - name: Build
        run: dotnet build src/Automate.sln --no-restore
      - name: Unit Test
        run: dotnet test --filter Category=Unit src/Automate.sln --no-build --verbosity normal
        #    - name: Integration Test
        #      run: dotnet test --filter Category=Integration src/Automate.sln --no-build --verbosity normal
      - name: Package (MacOS)
        run: dotnet publish --configuration Release -p:PublishSingleFile=true --self-contained true --runtime osx-x64 src/CLI/CLI.csproj
      - name: Upload Package (MacOS)
        uses: actions/upload-artifact@v2
        with:
          name: OSX-64 Binary
          path: src/CLI/bin/Release/net5.0/osx-x64/publish/
          if-no-files-found: error
      - name: Package (LinuxOS)
        run: dotnet publish --configuration Release -p:PublishSingleFile=true --self-contained true --runtime linux-x64 src/CLI/CLI.csproj
      - name: Upload Package (LinuxOS)
        uses: actions/upload-artifact@v2
        with:
          name: Linux-64 Binary
          path: src/CLI/bin/Release/net5.0/linux-x64/publish/
          if-no-files-found: error
      - name: Package (Windows)
        run: dotnet publish --configuration Release -p:PublishSingleFile=true --self-contained true --runtime win-x64 src/CLI/CLI.csproj
      - name: Upload Package (Windows)
        uses: actions/upload-artifact@v2
        with:
          name: Win64 Binary
          path: src/CLI/bin/Release/net5.0/win-x64/publish/
          if-no-files-found: error