name: Create Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-'
      - 'v[0-9]+.[0-9]+.[0-9]+-preview'

env:
  IS_CI_BUILD: 'true'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore src/Automate.sln
      - name: Build
        run: dotnet build src/Automate.sln --no-restore
      - name: NuGet Pack
        run: dotnet pack --configuration Release src/CLI/CLI.csproj
      - name: Upload NuGet
        uses: actions/upload-artifact@v2
        with:
          name: Nuget Binary
          path: src/CLI/nupkg/
          if-no-files-found: error
      - name: Create Publish folder
        run: mkdir "src/publish"
      - name: Package (MacOS)
        run: |
          dotnet publish --configuration Release -p:PublishSingleFile=true --self-contained true --runtime osx-x64 src/CLI/CLI.csproj
          copy "src/CLI/bin/Release/net6.0/osx-x64/publish/automate" "src/publish/automate.OSX-x64"
      - name: Upload Package (MacOS)
        uses: actions/upload-artifact@v2
        with:
          name: OSX-64 Binary
          path: src/CLI/bin/Release/net6.0/osx-x64/publish/
          if-no-files-found: error
      - name: Package (LinuxOS)
        run: |
          dotnet publish --configuration Release -p:PublishSingleFile=true --self-contained true --runtime linux-x64 src/CLI/CLI.csproj
          copy "src/CLI/bin/Release/net6.0/osx-x64/publish/automate" "src/publish/automate.Linux-x64"
      - name: Upload Package (LinuxOS)
        uses: actions/upload-artifact@v2
        with:
          name: Linux-64 Binary
          path: src/CLI/bin/Release/net6.0/linux-x64/publish/
          if-no-files-found: error
      - name: Package (Windows)
        run: |
          dotnet publish --configuration Release -p:PublishSingleFile=true --self-contained true --runtime win-x64 src/CLI/CLI.csproj
          copy "src/CLI/bin/Release/net6.0/win-x64/publish/automate.exe" "src/publish/automate.Win-x64.exe"
      - name: Upload Package (Windows)
        uses: actions/upload-artifact@v2
        with:
          name: Win-64 Binary
          path: src/CLI/bin/Release/net6.0/win-x64/publish/
          if-no-files-found: error
      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          prerelease: true
          draft: true
          generateReleaseNotes: true
          artifacts: "src/publish/automate.OSX-x64,src/publish/automate.Linux-x64,src/publish/automate.Win-x64.exe,src/CLI/nupkg/automate*.nupkg"
